# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gHxPO8YFPI7GdHVkD9MEPPJ-RnXzBSMf
"""

import torch
from torch import nn
import matplotlib.pyplot as plt
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
import numpy as np

# 1. Création du jeu de données
X, y = make_moons(n_samples=1000, noise=0.1, random_state=42)

# Conversion en tenseurs PyTorch
X = torch.from_numpy(X).type(torch.float)
y = torch.from_numpy(y).type(torch.float)

# Division entraînement/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Forme X_train: {X_train.shape}, y_train: {y_train.shape}")

class MoonModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer_stack = nn.Sequential(
            nn.Linear(in_features=2, out_features=10),
            nn.ReLU(),
            nn.Linear(in_features=10, out_features=10),
            nn.ReLU(),
            nn.Linear(in_features=10, out_features=1)
        )

    def forward(self, x):
        return self.layer_stack(x)

model = MoonModel()
display(model)

loss_fn = nn.BCEWithLogitsLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

def accuracy_fn(y_true, y_pred):
    correct = torch.eq(y_true, y_pred).sum().item()
    acc = (correct / len(y_pred)) * 100
    return acc

torch.manual_seed(42)
epochs = 1000

for epoch in range(epochs):
    model.train()
    y_logits = model(X_train).squeeze()
    y_pred = torch.round(torch.sigmoid(y_logits))

    loss = loss_fn(y_logits, y_train)
    acc = accuracy_fn(y_train, y_pred)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    model.eval()
    with torch.inference_mode():
        test_logits = model(X_test).squeeze()
        test_pred = torch.round(torch.sigmoid(test_logits))
        test_loss = loss_fn(test_logits, y_test)
        test_acc = accuracy_fn(y_test, test_pred)

    if epoch % 100 == 0:
        print(f"Époque: {epoch} | Perte: {loss:.5f}, Acc: {acc:.2f}% | Perte test: {test_loss:.5f}, Acc test: {test_acc:.2f}%")

    if test_acc > 96 and epoch > 200:
        print(f"Objectif atteint à l'époque {epoch}!")
        break

def plot_decision_boundary(model, X, y):
    x_min, x_max = X[:, 0].min() - 0.1, X[:, 0].max() + 0.1
    y_min, y_max = X[:, 1].min() - 0.1, X[:, 1].max() + 0.1
    xx, yy = np.meshgrid(np.linspace(x_min, x_max, 100), np.linspace(y_min, y_max, 100))

    model.eval()
    with torch.inference_mode():
        grid = torch.from_numpy(np.c_[xx.ravel(), yy.ravel()]).type(torch.float)
        probs = torch.sigmoid(model(grid)).reshape(xx.shape)

    plt.contourf(xx, yy, probs, levels=[0, 0.5, 1], cmap=plt.cm.RdYlBu, alpha=0.8)
    plt.scatter(X[:, 0], X[:, 1], c=y, s=40, cmap=plt.cm.RdYlBu, edgecolors='k')
    plt.title("Frontière de Décision")
    plt.show()

plot_decision_boundary(model, X_test, y_test)

"""## Exercice 2 : Classification Multiclasse (Spirales)"""

import numpy as np
import matplotlib.pyplot as plt
import torch
from torch import nn
from sklearn.model_selection import train_test_split

# Génération des données Spirales
N = 100 # points par classe
D = 2 # dimensions
K = 3 # classes
X_np = np.zeros((N*K,D))
y_np = np.zeros(N*K, dtype='uint8')
for j in range(K):
  ix = range(N*j,N*(j+1))
  r = np.linspace(0.0,1,N)
  t = np.linspace(j*4,(j+1)*4,N) + np.random.randn(N)*0.2
  X_np[ix] = np.c_[r*np.sin(t), r*np.cos(t)]
  y_np[ix] = j

plt.scatter(X_np[:, 0], X_np[:, 1], c=y_np, s=40, cmap=plt.cm.Spectral)
plt.title("Jeu de données en Spirales")
plt.show()

X_spiral = torch.from_numpy(X_np).type(torch.float)
y_spiral = torch.from_numpy(y_np).type(torch.long)

X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(X_spiral, y_spiral, test_size=0.2, random_state=42)

class SpiralModel(nn.Module):
    def __init__(self, input_features, output_features, hidden_units=64):
        super().__init__()
        self.linear_layer_stack = nn.Sequential(
            nn.Linear(in_features=input_features, out_features=hidden_units),
            nn.ReLU(),
            nn.Linear(in_features=hidden_units, out_features=hidden_units),
            nn.ReLU(),
            nn.Linear(in_features=hidden_units, out_features=output_features)
        )

    def forward(self, x):
        return self.linear_layer_stack(x)

model_s = SpiralModel(input_features=2, output_features=3)
display(model_s)

loss_fn_s = nn.CrossEntropyLoss()
optimizer_s = torch.optim.Adam(model_s.parameters(), lr=0.01)

torch.manual_seed(42)
epochs = 1000

for epoch in range(epochs):
    model_s.train()
    y_logits = model_s(X_train_s)
    y_pred = torch.softmax(y_logits, dim=1).argmax(dim=1)

    loss = loss_fn_s(y_logits, y_train_s)
    acc = (y_pred == y_train_s).sum().item() / len(y_train_s) * 100

    optimizer_s.zero_grad()
    loss.backward()
    optimizer_s.step()

    model_s.eval()
    with torch.inference_mode():
        test_logits = model_s(X_test_s)
        test_pred = torch.softmax(test_logits, dim=1).argmax(dim=1)
        test_loss = loss_fn_s(test_logits, y_test_s)
        test_acc = (test_pred == y_test_s).sum().item() / len(y_test_s) * 100

    if epoch % 100 == 0:
        print(f"Époque: {epoch} | Perte: {loss:.4f}, Acc: {acc:.2f}% | Test Acc: {test_acc:.2f}%")

    if test_acc > 95:
        print(f"Précision cible atteinte à l'époque {epoch} : {test_acc:.2f}%")
        break

def plot_multiclass_boundary(model, X, y):
    x_min, x_max = X[:, 0].min() - 0.1, X[:, 0].max() + 0.1
    y_min, y_max = X[:, 1].min() - 0.1, X[:, 1].max() + 0.1
    xx, yy = np.meshgrid(np.linspace(x_min, x_max, 100), np.linspace(y_min, y_max, 100))

    model.eval()
    with torch.inference_mode():
        grid = torch.from_numpy(np.c_[xx.ravel(), yy.ravel()]).type(torch.float)
        logits = model(grid)
        preds = torch.softmax(logits, dim=1).argmax(dim=1).reshape(xx.shape)

    plt.contourf(xx, yy, preds, cmap=plt.cm.Spectral, alpha=0.8)
    plt.scatter(X[:, 0], X[:, 1], c=y, s=40, cmap=plt.cm.Spectral, edgecolors='k')
    plt.title("Frontière de Décision - Spirales")
    plt.show()

plot_multiclass_boundary(model_s, X_test_s, y_test_s)

